[package]
name = "batch_oper"
version = "1.12.0"
authors = ["BatchOperator", "Package <Aditrc@outlook.com>"]
edition = "2018"
description = "batch_oper provides some batch operation macro for some operations"
repository = "https://github.com/BatchOperator/BatchOperRust"
license = "MIT"
keywords = ["batch_oper", "macro", "using", "in", "let_chain"]
categories = ["algorithms", "api-bindings", "development-tools", "no-std"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
default = ["std", "combin", "named-into", "macro-lit", "side-effect", "re-exports", "chain_panic", "chain_todo"]
std = []
combin = []
combin-mutual = []
named-into = []
macro-lit = []
re-exports = []
side-effect = []
chain_panic = []
chain_todo = []